# DigitalOcean App Platform Specification for SafePing
spec:
  name: safeping-production
  region: nyc
  
  # Domains configuration
  domains:
    - domain: safeping.app
      type: PRIMARY
      zone: safeping.app
    - domain: www.safeping.app
      type: ALIAS
      zone: safeping.app
    - domain: web.safeping.app
      type: ALIAS
      zone: safeping.app
    - domain: my.safeping.app
      type: ALIAS
      zone: safeping.app

  # Docker container service
  services:
    - name: safeping-app
      dockerfile_path: Dockerfile
      source_dir: /
      
      # GitHub integration
      github:
        repo: kiwidigitalnz/SafePing
        branch: main
        deploy_on_push: true
      
      # Instance configuration
      instance_size_slug: basic-xxs  # $4/month
      instance_count: 1
      
      # HTTP port
      http_port: 80
      
      # Health check
      health_check:
        http_path: /health
        initial_delay_seconds: 10
        period_seconds: 30
        timeout_seconds: 5
        success_threshold: 1
        failure_threshold: 3
      
      # Environment variables
      envs:
        # Supabase Configuration
        - key: VITE_SUPABASE_URL
          scope: BUILD_TIME
          value: ${SUPABASE_URL}
        - key: VITE_SUPABASE_ANON_KEY
          scope: BUILD_TIME
          value: ${SUPABASE_ANON_KEY}
        
        # Application URLs (updated to web.safeping.app)
        - key: VITE_APP_URL
          scope: BUILD_TIME
          value: https://web.safeping.app
        - key: VITE_PWA_URL
          scope: BUILD_TIME
          value: https://my.safeping.app
        - key: VITE_LANDING_URL
          scope: BUILD_TIME
          value: https://safeping.app
        
        # Contact Information
        - key: VITE_CONTACT_EMAIL
          scope: BUILD_TIME
          value: legal@safeping.app
        
        # Google OAuth
        - key: VITE_GOOGLE_CLIENT_ID
          scope: BUILD_TIME
          value: ${GOOGLE_CLIENT_ID}
        
        # Stripe
        - key: VITE_STRIPE_PUBLIC_KEY
          scope: BUILD_TIME
          value: ${STRIPE_PUBLIC_KEY}
        
        # Push Notifications
        - key: VITE_VAPID_PUBLIC_KEY
          scope: BUILD_TIME
          value: ${VAPID_PUBLIC_KEY}
        
        # Build configuration
        - key: NODE_ENV
          scope: BUILD_TIME
          value: production
        
      # Build command (handled by Dockerfile)
      build_command: ""
      
      # Run command (handled by Dockerfile)
      run_command: ""

  # Alerts (optional)
  alerts:
    - rule: DEPLOYMENT_FAILED
    - rule: DOMAIN_FAILED
    - rule: DEPLOYMENT_LIVE

# Environment variables to set in DigitalOcean dashboard:
# SUPABASE_URL - Your Supabase project URL
# SUPABASE_ANON_KEY - Your Supabase anonymous key
# GOOGLE_CLIENT_ID - Your Google OAuth client ID
# STRIPE_PUBLIC_KEY - Your Stripe publishable key
# VAPID_PUBLIC_KEY - Your VAPID public key for push notifications
