name: Simple Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY }}/safeping-production:latest
            registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY }}/safeping-production:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Success message
        run: |
          echo "✅ Docker image built and pushed successfully!"
          echo "DigitalOcean will automatically deploy from the registry."
          echo "Check deployment status in your DigitalOcean dashboard."
